### ISSUE TITLE
关于配置部分说明的开机启动部分

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#10]
由于开机时某些组件的加载时间原因，直接在rc.local按文档写入内容可能存在唤醒失效（只有启动语音，扫面微信和语音唤醒均无反应）的情况。建议修改说明在前面增加 sleep 5。

另外，启动树莓派的部分最好把绝对路径也加上……严谨严谨……

**Comment by wzpan** [comment]
done.
