### ISSUE TITLE
建议：主动唤醒的接口

### ISSUE THREAD

**Issue by helloyinwei** [wzpan/dingdang-robot#106]
插件的接口都是收到信号后的被动唤醒  
是否可以开发主动唤醒的接口  
可以用在需要定时或者循环执行的任务上  
比如每隔一段时间查询天气预警信息，查询到有预警之后进行输出

**Comment by wzpan** [comment]
你说的这个，可以用ifttt实现关联。http://www.hahack.com/codes/easiest-way-to-make-dingdang-watch-events/

**Comment by helloyinwei** [comment]
ifttt使用，有语音输出但无法将插件输出微信的结果输出到微信

**Comment by wzpan** [comment]
@helloyinwei 你也可以参照 [notifiers](https://github.com/wzpan/dingdang-robot/blob/master/client/notifier.py) 自己写多一个 handlexxx 函数，实现对应的主动轮询检查。目前邮件、日程管理就是基于主动轮询检查的。无需主动唤醒。
