### ISSUE TITLE
Makefile:51: recipe for target 'Phonetisaurus.o' failed

### ISSUE THREAD

**Issue by YountMan** [wzpan/dingdang-robot#107]
大佬好, 按照 https://github.com/wzpan/dingdang-robot/wiki/install 给出的安装步骤  进行到<br/>>  ###编译安装 Phonetisaurus： ###sudo make  的时候 出现 错误 以下是错误最近一行的信息

<pre style="color:red">
/usr/local/include/fst/bi-table.h:125:9: error: declaration of ‘struct fst::HashSet<int, fst::CompactHashBiTable<int, fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::ComposeHash<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > >, std::equal_to<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > >, (fst::HSType)1u>::HashFunc, fst::CompactHashBiTable<int, fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> >, fst::ComposeHash<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > >, std::equal_to<fst::DefaultComposeStateTuple<int, fst::IntegerFilterState<signed char> > >, (fst::HSType)1u>::HashEqual, (fst::HSType)1u>’
 struct  HashSet : public unordered_set<K, H, E, PoolAllocator<K> > {
         ^
Makefile:51: recipe for target 'Phonetisaurus.o' failed
make: *** [Phonetisaurus.o] Error 1
</pre>

有人遇到过么? 希望大佬有时间帮忙看看是什么问题 
build 180121
 补上系统信息及版本信息
<pre>
pi@pi_ssd:~ $ uname -a
Linux pi_ssd 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
pi@pi_ssd:~ $ cat /proc/version
Linux version 4.9.35-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1014 SMP Fri Jun 30 14:47:43 BST 2017
pi@pi_ssd:~ $ cat /etc/issue
Raspbian GNU/Linux 8 \n \l

pi@pi_ssd:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

pi@pi_ssd:~/Downloads/is2013-conversion/phonetisaurus/src $ ls -l
总用量 248
drwxr-xr-x 4 pi pi  4096 3月  18  2013 3rdparty
-rw-r--r-- 1 pi pi  7200 3月  18  2013 Arpa2Fst.cpp
-rw-r--r-- 1 pi pi  3596 3月  18  2013 Arpa2Fst.hpp
-rw-r--r-- 1 pi pi  9003 3月  18  2013 ARPA2WFST.cpp
-rw-r--r-- 1 pi pi  3222 3月  18  2013 ARPA2WFST.hpp
-rw-r--r-- 1 pi pi  3326 3月  18  2013 FstPathFinder.cpp
-rw-r--r-- 1 pi pi  3435 3月  18  2013 FstPathFinder.hpp
-rw-r--r-- 1 pi pi  5256 3月  18  2013 LatticePruner.cpp
-rw-r--r-- 1 pi pi  2677 3月  18  2013 LatticePruner.hpp
-rw-r--r-- 1 pi pi 15151 3月  18  2013 M2MFstAlignerB.cpp
-rw-r--r-- 1 pi pi  4996 3月  18  2013 M2MFstAlignerB.hpp
-rw-r--r-- 1 pi pi 20524 3月  18  2013 M2MFstAligner.cpp
-rw-r--r-- 1 pi pi  4956 3月  18  2013 M2MFstAligner.hpp
-rw-r--r-- 1 pi pi  3113 4月  15  2013 Makefile
-rw-r--r-- 1 pi pi 28252 3月  18  2013 MBRDecoder.cpp
-rw-r--r-- 1 pi pi  4130 3月  18  2013 MBRDecoder.hpp
-rw-r--r-- 1 pi pi 12217 4月  14  2013 phonetisaurus-align.cpp
-rw-r--r-- 1 pi pi  2994 3月  18  2013 phonetisaurus-arpa2fst.cpp
-rw-r--r-- 1 pi pi  2664 3月  18  2013 phonetisaurus-arpa2wfst-omega.cpp
-rw-r--r-- 1 pi pi 10865 3月  18  2013 Phonetisaurus.cpp
-rw-r--r-- 1 pi pi 11887 3月  18  2013 PhonetisaurusE2F.cpp
-rw-r--r-- 1 pi pi  2877 3月  18  2013 PhonetisaurusE2F.hpp
-rw-r--r-- 1 pi pi  5355 3月  18  2013 phonetisaurus-g2p.cpp
-rw-r--r-- 1 pi pi  5550 3月  18  2013 phonetisaurus-g2p-omega.cpp
-rw-r--r-- 1 pi pi  2752 3月  18  2013 Phonetisaurus.hpp
-rw-r--r-- 1 pi pi 13413 3月  18  2013 PhonetisaurusOmega.cpp
-rw-r--r-- 1 pi pi  3391 3月  18  2013 PhonetisaurusOmega.hpp
-rw-r--r-- 1 pi pi  4375 3月  18  2013 util.cpp
-rw-r--r-- 1 pi pi  2039 3月  18  2013 util.hpp
pi@pi_ssd:~/Downloads/is2013-conversion/phonetisaurus/src $ df -h
文件系统        容量  已用  可用 已用% 挂载点
/dev/root        30G   13G   16G   47% /
devtmpfs        458M     0  458M    0% /dev
tmpfs           462M     0  462M    0% /dev/shm
tmpfs           462M   48M  415M   11% /run
tmpfs           5.0M     0  5.0M    0% /run/lock
tmpfs           462M     0  462M    0% /sys/fs/cgroup
/dev/mmcblk0p1  1.9G   23M  1.9G    2% /boot
tmpfs            93M  8.0K   93M    1% /run/user/1000
/dev/sda1        63M   21M   43M   34% /media/pi/boot
pi@pi_ssd:~/Downloads/is2013-conversion/phonetisaurus/src $ 

</pre>

**Comment by wzpan** [comment]
什么版本的系统？

**Comment by YountMan** [comment]
Duplicate of #103 pi@pi_ssd:~ $ uname -a
Linux pi_ssd 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
pi@pi_ssd:~ $ cat /proc/version
Linux version 4.9.35-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1014 SMP Fri Jun 30 14:47:43 BST 2017
pi@pi_ssd:~ $ cat /etc/issue
Raspbian GNU/Linux 8 \n \l

pi@pi_ssd:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
pi@pi_ssd:~ $

**Comment by YountMan** [comment]
build 180121
解决了， Google 到的 <br/>
贴出地址 ： https://github.com/jasperproject/jasper-client/issues/267<br/>
变更为   <code>sudo  CPPFLAGS="-std=c++11" make</code> <br/>
make 通过
 还是 多谢@wzpan 大佬的回复
