### ISSUE TITLE
镜像中系统源替换不彻底

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#11]
只替换了raspbian源，没有替换raspi源（这个源貌似是Debian系统已经抛弃但是Raspbian还在使用的软件包的源，据观察，阿里云上没有这一目录，只有ustc有……）：
Quote:
修改/etc/apt/sources.list.d/raspi.list为以下内容：
deb https://mirrors.ustc.edu.cn/archive.raspberrypi.org/ jessie main ui

（经个人测试……感觉ustc的速度比阿里云快……）
Quote:
编辑/etc/apt/sources.list文件。删除原文件所有内容，用以下内容取代：
deb http://mirrors.ustc.edu.cn/raspbian/raspbian/ jessie main non-free contrib
deb-src http://mirrors.ustc.edu.cn/raspbian/raspbian/ jessie main non-free contrib

**Comment by GoldJohnKing** [comment]
还有一件事……镜像系统提供的resource.list的第二个源的最后少了个"/"，本强迫症建议有机会加上……

**Comment by wzpan** [comment]
你的个人测试未必能代表所有人的速度：

``` sh
pi@raspberrypi:~/dingdang $ sudo apt-get update
忽略 https://mirrors.ustc.edu.cn jessie InRelease      
错误 http://mirrors.ustc.edu.cn jessie InRelease        
  
错误 http://mirrors.ustc.edu.cn jessie Release.gpg      
  无法发起与 mirrors.ustc.edu.cn:80 (2001:da8:d800:95::110) 的连接 - connect (101: 网络不可达) [IP: 2001:da8:d800:95::110 80]

```

**Comment by GoldJohnKing** [comment]
我的错……不是https而应该是http。
另外，据我了解，http://mirrors.ustc.edu.cn/archive.raspberrypi.org/ 这个镜像好像只有USTC有，没在阿里云或者163里找到。所以raspi.list要是换成国内的话，也就只能填这个了。

<img src="http://z4a.net/images/2017/08/12/mirrors.ustc.edu.cnraspbianraspbian.png" alt="mirrors.ustc.edu.cnraspbianraspbian.png" border="0">
<img src="http://z4a.net/images/2017/08/12/pingmirrors.ustc.edu.cnraspbianraspbian.png" alt="pingmirrors.ustc.edu.cnraspbianraspbian.png" border="0">
<img src="http://z4a.net/images/2017/08/12/httpmirrors.ustc.edu.cnraspbianraspbian.png" alt="httpmirrors.ustc.edu.cnraspbianraspbian.png" border="0">

**Comment by wzpan** [comment]
新版镜像即将发布，加了 raspi.list 的镜像源。其他的保持阿里云镜像不变。补上了 `/` 。
