### ISSUE TITLE
手动安装有两个文件下不了。

### ISSUE THREAD

**Issue by tomcatGu** [wzpan/dingdang-robot#118]
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/m2m-aligner/m2m-aligner-1.2.tar.gz

wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/phonetisaurus/is2013-conversion.tgz

怎么办？

**Comment by tomcatGu** [comment]
这两个不装有对软件使用有影响吗？

**Comment by wzpan** [comment]
群文件里有
