### ISSUE TITLE
请问，我手动安装完成后，PocketSphinx 识别到了的一直都是 ['']，请问是什么原因？

### ISSUE THREAD

**Issue by wuliang142857** [wzpan/dingdang-robot#123]
日志：

<img width="1162" alt="2018-02-21 18 38 56" src="https://user-images.githubusercontent.com/93135/36475749-a4f76f8a-1736-11e8-8538-fd1dac20b0a3.png">

几种语音合成我都试过，都是这样的，请问能判断出来是什么原因造成的吗？

**Comment by wzpan** [comment]
可能是麦克风没有配置正确，参考wiki，做到arecord、aplay可录可播再试。

**Comment by wuliang142857** [comment]
@wzpan 我arecord、aplay都是可以的，试过很多遍的。我打开 alsamixer ， 默认的声卡不是seeed，而是系统自带的那个，请问会是这个原因吗？
另外，我openfst是apt-get安装的，不是源码编译的，这个会是可能吗？

**Comment by wzpan** [comment]
> 我打开 alsamixer ， 默认的声卡不是seeed，而是系统自带的那个，请问会是这个原因吗？

有可能。.asoundrc 配置好了没？

openfst 应该不会导致这个问题。

**Comment by wuliang142857** [comment]
我配置了.asoundrc ，果然是因为这个文件没有配对，谢谢
