### ISSUE TITLE
请问HomeAssistant的配置文件在哪个文件夹下面

### ISSUE THREAD

**Issue by jay771488802** [wzpan/dingdang-robot#130]
请问HomeAssistant的配置文件configuration.yaml和customize.yaml在哪里面呢，用find命令找不到啊

**Comment by wzpan** [comment]
你得参考 HomeAssistant 的官方指南，放在他们要求的地方。可能是另一个账户下。

**Comment by jay771488802** [comment]
您好，非常感谢您的回复！
我去HomeAssistant官网上查看过了。我理解是叮当并没有安装HomeAssistant，而是可以通过叮当声音控制接入HomeAssistant的设备，对吗？

**Comment by wzpan** [comment]
对的

**Comment by jay771488802** [comment]
请问下面的配置命令是在哪个文件夹的哪个文件中呢，我没有找到它在什么位置。
homeassistant:
    url: "http://127.0.0.1"    #切记加上http://，ip或者域名为你的homeassistant的主机
    port: "8123"               # 端口为你的homeassistant的端口
    password: ""               # 建议加上密码，增加安全性
