### ISSUE TITLE
录音问题

### ISSUE THREAD

**Issue by JasonIonke** [wzpan/dingdang-robot#134]
请教一下各位，测试录音功能时使用
 arecord -d 20  -f S16_LE  temp.wav 可以录音
但使用 arecord -d 20  temp.wav 录下的都是噪音，是否需要在dingdang里把 -f S16_LE也设置进去？如何设置呢？

因为现在启动python dingdang.py会显示如下错误，感觉是录音没设置好。
谢谢！

![image](https://user-images.githubusercontent.com/37280348/37343578-f0ac0856-2702-11e8-859e-51eae7a44b0a.png)

**Comment by wzpan** [comment]
先看下 troubleshooting：https://github.com/wzpan/dingdang-robot/wiki/troubleshooting

**Comment by JasonIonke** [comment]
去看了，我先去解决overflow的问题试试，谢谢wzpan！
