### ISSUE TITLE
指令无法识别

### ISSUE THREAD

**Issue by wzr12345** [wzpan/dingdang-robot#138]
![default](https://user-images.githubusercontent.com/4144747/37557721-ed3c711c-2a43-11e8-9b6e-9abf0e678aab.PNG)
启动后能听到机器人说我能为您做什么,接下来说了也没有反应,然后我就按下ctrl+z.
我发现traceboak跟troubleshooting中的启动后报错,相似,可是dingdong的进程终止了,还是运行不了

**Comment by wzpan** [comment]
arecord，aplay 能否正常工作？

**Comment by wzr12345** [comment]
yes, ceshi meiyou wenti.
nengluyin ,nengting.


--------------原始邮件--------------
发件人："Joseph Pan "<notifications@github.com>;
发送时间：2018年3月18日(星期天) 凌晨0:43
收件人："wzpan/dingdang-robot" <dingdang-robot@noreply.github.com>;
抄送："vegasue "<16020228@mail.szpt.edu.cn>;"Author "<author@noreply.github.com>;
主题：Re: [wzpan/dingdang-robot] 指令无法识别 (#138)
-----------------------------------

arecord，aplay 能否正常工作？

**Comment by wzpan** [comment]
要说唤醒词“嘿叮当”才能唤醒叮当

**Comment by wzr12345** [comment]
是的，他能识别到 [heidingdang],随即我说 唱歌，然后就显示 "info nothinghas been said or transcribed" 循环。先睡了，晚安

**Comment by wzpan** [comment]
识别到会响滴一声，滴一声了再说话

**Comment by wzr12345** [comment]
成功了,问题出现在我修改了
robot_name: 'DINGDANG'  # 必须使用大写
robot_name_cn: '叮当'
    起先,我看到提醒词是"heydingdang",与这个robot_name是"dingdang",没有关系,所以我就改变了robot_name.
自己理解错误
感谢您的指导
♪(＾∀＾●)ﾉ
