### ISSUE TITLE
更换唤醒词时遇到错误

### ISSUE THREAD

**Issue by tonylkc** [wzpan/dingdang-robot#14]
Languagemodel 能成功生成，然后在生成 Dictionary的时候出现这错误： 

> phonetisaurus-g2p: error while loading shared libraries: libfst.so.1: cannot open shared object file: No such file or directory

我是用镜像源直接用的

谢谢

**Comment by wzpan** [comment]
不需要手动生成 languagemodel 和 dictionary 。而是到 lmtool 里生成。
方法详见 [修改唤醒词](https://github.com/wzpan/dingdang-robot/wiki/configuration#%E4%BF%AE%E6%94%B9%E5%94%A4%E9%86%92%E8%AF%8D) 。

**Comment by wzpan** [comment]
问题应该能解决。关闭本issue。
