### ISSUE TITLE
开机教程中创建软链接部分存在问题

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#15]
开机教程中创建软链接部分存在问题。

经测试，创建的软链接仅包含软链接本身，不含其中任何文件。打开软链接后ls -ln显示没有任何东西。因此会导致sudo启动失败。本人确定输入的指令与教程完全相同。

推测是root目录默认权限有问题。
尝试过用root身份对/root目录进行chmod 777操作，照样不好使。
后来，本人用root身份 rm -rf /root，然后重新mkdir /root，再重新建立软链接，成功启动叮当，软链接中也出现了对应文件。重建后的root文件夹权限为：drwxr-xr-x。之前的root权限未做记录。

本人初步接触Linux，水平实在有限，烦请进行测试，完善教程。

**Comment by wzpan** [comment]
问题未能复现：

``` sh
pi@raspberrypi:~/dingdang $ sudo ln -s /home/pi/.dingdang /root/.dingdang
pi@raspberrypi:~/dingdang $ sudo ls /root/.dingdang
contrib  profile.yml  vocabularies
pi@raspberrypi:~/dingdang $ 
```

**Comment by GoldJohnKing** [comment]
这就惨淡了……群里也有人发生过类似的情况。
可能是最开始做过软链接，删了又重建出现的状况……

个人建议可以考虑在Wiki的FAQ部分增加如下内容：
（我吃完饭过来补……）（已补完）

————————————————————————————————

启动叮当失败，提示“No Such File or Directory”，或者在编译阶段直接闪退：
1. 首先，确认/home/pi/.dingdang目录及其中文件是否存在。若不存在，参考[手动安装](https://github.com/wzpan/dingdang-robot/wiki/install#%E5%AE%89%E8%A3%85%E5%8F%AE%E5%BD%93-1)部分进行创建。
2. 若存在，确认叮当是否以sudo权限启动。
若以sudo权限启动，确认/root目录中.dingdang软链接是否存在。
若不存在，参考[开机启动教程](https://github.com/wzpan/dingdang-robot/wiki/configuration#%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8)创建之。若软链接存在但仍无法正常启动，执行以下操作：
`sudo rm -rf /root`
`cd`
`mkdir /root`
然后[重新建立软链接](https://github.com/wzpan/dingdang-robot/wiki/configuration#%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8)。

**Comment by wzpan** [comment]
哇这不行，直接删 /root 是不靠谱的。万一里头有超级用户其他的数据的？

**Comment by GoldJohnKing** [comment]
……这倒也是……(尴尬)……
