### ISSUE TITLE
只要日志出现“[DEBUG] sync_check: -1 -1”，就会发生识别开始与停止时间难以把握。

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#16]
只要日志出现“[DEBUG] sync_check: -1 -1”，就会发生识别开始与停止时间难以把握，基本录不上。
运气好能赶上两个字，不好的话一个字都识别不上，而且还不一定慢多少或者快多少……时间实在难以把握。

我不太懂这个……但是有没有可能是将“滴滴”音和录音的开始次序调换之后，其他有关的代码没有同步修改……？我记得之前出现这个不会出现这种情况。

比如……录音与播放滴滴音的校正offset应该由-1秒改为0或者+1秒之类的……？

还有，个人感觉目前的识别停止时间比较短促……现在的状态是“嘿叮当”，“滴滴”直接就“嘟嘟”了……必须在听到“滴滴”的时候说而不是在“滴滴”停止的时候说。建议在群里发个投票，看看用不用+1s……

**Comment by wzpan** [comment]
现在主动聆听已经调整，不会很短促
