### ISSUE TITLE
location of phonetisaurus-g2p is wrong

### ISSUE THREAD

**Issue by swizardlv** [wzpan/dingdang-robot#2]
`sudo cp ~/phonetisaurus-0.7.8/phonetisaurus-g2p /usr/local/bin/phonetisaurus-g2p`
should be changed to 
`sudo cp ~/is2013-conversion/bin/phonetisaurus-g2p /usr/local/bin/phonetisaurus-g2p`

**Comment by wzpan** [comment]
Fixed. Thanks for reporting.
