### ISSUE TITLE
最新版本的robot.py存在问题。

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#22]
今天更新过emotibot之后的问题。
robot.py文件中第167行里那个末有“[0]”，删去才能正常调用Emotibot。

 啊对了……另外建议修缮一下操作的语音提示。比如在“即将播放”后面加个冒号以及在“歌手-歌名”之间增加个逗号，增加个停顿之类的……这些细节对体验而言很重要啊……

（我没研究明白Git，要不我就弄pull request了……）

**Comment by wzpan** [comment]
> robot.py文件中第162行里那个末有“[0]”，删去才能正常调用Emotibot。

已修复。

> 另外建议修缮一下操作的语音提示。比如在“即将播放”后面加个冒号以及在“歌手-歌名”之间增加个逗号，增加个停顿之类的

done。谢谢建议。

**Comment by GoldJohnKing** [comment]
今天Git pull 了一下，robot.py中167行末尾的[0]并没有删去……

**Comment by wzpan** [comment]
[0] 并不是导致问题的原因，而且是得主动模式下必须的。现在不会出问题的。

**Comment by GoldJohnKing** [comment]
但是不删没法用啊……

错误提示如下：
```
INFO:client.stt:百度语音识别到了: 你好，
CRITICAL:client.robot:Emotibot failed to responsed for '\xe4\xbd\xa0\xe5\xa5\xbd\xef\xbc\x8c'
Traceback (most recent call last):
  File "/home/pi/dingdang/client/robot.py", line 167, in chat
    result = '\n'.join(responds)
TypeError: sequence item 0: expected string, dict found
```

**Comment by wzpan** [comment]
再更新下试试

**Comment by GoldJohnKing** [comment]
OK。问题解决。（但是我emotibot设的是“active_mode: true”啊……）
