### ISSUE TITLE
Wiki配置中又有一个小问题……

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#23]
yml部分
原文：
/# snowboy 唤醒SST引擎（可选）
/# https://snowboy.kitt.ai/dashboard
snowboy:
    model: '/home/pi/dingdang/client/snowboy/`**_dingdangdingdang.pmdl_**`
/# 唤醒词模型
    sensitivity: "0.5"  # 敏感度

其中的`**_dingdangdingdang.pmdl_**`。

**Comment by wzpan** [comment]
? 没有啊

**Comment by wzpan** [comment]
dingdangdingdang.pmdl 是真的有这个文件。

**Comment by GoldJohnKing** [comment]
我这里的是dingdang.pmdl……我不记得我改过……

**Comment by wzpan** [comment]
两个都有
