### ISSUE TITLE
hardware choices WIKI页面关于PlayStation Eye的描述有误

### ISSUE THREAD

**Issue by yunxiyinzhe** [wzpan/dingdang-robot#24]
麦克风-四阵列：

> PS4 eyes - PS4 淘汰的配件，包含四阵列麦克风和摄像头，免驱使用。由于是淘汰下来的配件，价格也比较便宜，可以到淘宝上找找。

PS4 eyes应该修改为PS3 Eye或者PlayStation Eye,属于PS3的淘汰配件。

**Comment by wzpan** [comment]
已改
