### ISSUE TITLE
集成 HomeAssistant

### ISSUE THREAD

**Issue by wzpan** [wzpan/dingdang-robot#29]
与 HomeAssistant 结合，通过语音控制 HASS 的插件。可参考：

1. https://home-assistant.io/components/alexa/#i-want-to-build-custom-commands-to-use-with-echo
2. https://github.com/romulcah/jasper-home-assistant-io-integration/blob/master/WhoIsHome.py

**Comment by chen-sky** [comment]
可以开发官方插件吗？ @wzpan

**Comment by wzpan** [comment]
#38 review 中

**Comment by wzpan** [comment]
merged
