### ISSUE TITLE
镜像安装后，离线可识别唤醒，百度在线识别无反应

### ISSUE THREAD

**Issue by 604470287** [wzpan/dingdang-robot#36]

**Comment by wzpan** [comment]
麦克风的问题，建议换用阵列型麦克风。详见 [硬件选购建议](https://github.com/wzpan/dingdang-robot/wiki/hardware-choices)

**Comment by 604470287** [comment]
谢谢你的建议。我换HOSODO HSD-M20试试。
这个音箱+麦克风和开源项目中的一样，能够使用吧？

**Comment by wzpan** [comment]
能使用，虽然已经不是我推荐的方案。
