### ISSUE TITLE
logo征集

### ISSUE THREAD

**Issue by wzpan** [wzpan/dingdang-robot#39]
征集叮当机器人的logo，将被用在项目主页、QQ群头像、论坛等多处。

欢迎贡献~~~

**Comment by GoldJohnKing** [comment]
先报个名……最近事多……等稳定下来之后就尽力做一个……

顺路提一下……下次准备做镜像之前麻烦在群里说一声……我把给叮当搞的启动时自动更新的东西提个issue上来。

**Comment by GoldJohnKing** [comment]
先贴一下目前的几个方案的草图。是草图，定夺之后还要按比例和尺寸重画一下。要不缩放之后的清晰度相当惨淡……

prefer方案：
<img src="https://www.z4a.net/images/2017/09/17/Pref.png" alt="Pref.png" border="0">

4号方案：
<a href="https://www.z4a.net/image/oChsU"><img src="https://www.z4a.net/images/2017/09/17/4.png" alt="4.png" border="0" /></a>

0号方案：
<img src="https://www.z4a.net/images/2017/09/17/0.png" alt="0.png" border="0">

1号方案：
<img src="https://www.z4a.net/images/2017/09/17/1.png" alt="1.png" border="0">

2号方案：
<img src="https://www.z4a.net/images/2017/09/17/2.png" alt="2.png" border="0">

3号方案：
脑洞太大，被我掐死了。

**Comment by GoldJohnKing** [comment]
方案4带字样透明精修SVG矢量无限放大不花版样图：
<img src="http://z4a.net/images/2017/09/18/4-.png" alt="4-.png" border="0" />
其实我感觉是不是把字样前面的ding关于中轴做个对称比较好……就是大脑在中间，字样按阅读顺序从中间依次向左右排列……？

**Comment by wzpan** [comment]
ing和ang黑色吧，另外字弄小一点。再单独给一张没字的
