### ISSUE TITLE
镜像地址钉盘失效

### ISSUE THREAD

**Issue by smileorigin** [wzpan/dingdang-robot#49]
我上传了到钉盘了，地址：https://space.dingtalk.com/s/gwHN4rkCzhPON_0D2gAgNjMwNTQ2YThjN2U2NGUyZmI3Y2EwMTNlMWExNGM2ODQ 
密码: hhAN

**Comment by wzpan** [comment]
已添加至wiki，谢谢。

**Comment by smileorigin** [comment]
互帮互助，更应该感谢的您开源这个项目，大家一起壮大 棒棒哒，我也很想为这个项目尽一份微薄之力

**Comment by wzpan** [comment]
哈哈，有的是机会。期待你的继续贡献～～～
