### ISSUE TITLE
pocketsphinx离线语音库增添功能

### ISSUE THREAD

**Issue by linmoson** [wzpan/dingdang-robot#58]
如题所说，比如唤醒词是叮当，但是我想加一个亮灯的功能，自己已经写好源代码led.py（灯就直接插在树莓派板子上）。
当我说“亮灯”——哪怕说light时,能识别出来直接亮灯（不用调用在线API）；而当我说“叮当”的时候，又能切换回叮当主程序，去调用在线API和stt
希望有大佬能给一点启发~
这边自己看了一个用pocketsphinx下面的continuous.c的方式来弄的，虽然可以做到语音控制亮灯，但是无法和叮当兼容~

**Comment by wzpan** [comment]
其实你这个需求，完全不需要集成进叮当，另外启动一个进程监听亮灯的指令就行了。

**Comment by linmoson** [comment]
我可以理解为开机时，同时自动启动两个程序，一个负责监听叮当这个唤醒词，另一个负责监听这边开灯的指令吗？但是这样相当于要编辑两套pocketsphinx 的语言字典，可以做到吗？本人linux完全是入门阶段，不是很懂，看别人编译不知是configure还是make指令，不会将两个字典弄混吗？
发自网易邮箱大师
在2017年10月14日 11:14，Joseph Pan 写道： 其实你这个需求，完全不需要集成进叮当，另外启动一个进程监听亮灯的指令就行了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wzpan/dingdang-robot","title":"wzpan/dingdang-robot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wzpan/dingdang-robot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wzpan in #58: 其实你这个需求，完全不需要集成进叮当，另外启动一个进程监听亮灯的指令就行了。"}],"action":{"name":"View Issue","url":"https://github.com/wzpan/dingdang-robot/issues/58#issuecomment-336605820"}}}

**Comment by wzpan** [comment]
不会弄混啊，两个不同的程序。
