### ISSUE TITLE
在Ubuntu Touch上会会导致重启

### ISSUE THREAD

**Issue by 467815891a** [wzpan/dingdang-robot#6]
想在Ubuntu Touch 上运行这个项目，完全按照手动安装的步骤来的，中途也没有出错。
python dingdang.py之后，ubuntu touch就死机重启了。。。

phablet@ubuntu-phablet:~/dingdang$ python dingdang.py 
 *******************************************************
 *             叮当 - 中文语音对话机器人               *
 *          (c) 2017 潘伟洲 <m@hahack.com>             *
 *   https://github.com/wzpan/dingdang-robot.git       *
 *******************************************************
[root@localhost wei]# 

系统日志什么也没记录下来，请问有没有可能找到原因？

**Comment by wzpan** [comment]
看不出原因来……重启的原因可能是硬件自身的问题。

**Comment by 467815891a** [comment]
多谢，我还是在树莓派上弄吧。
感谢你的项目，真的很棒！
