### ISSUE TITLE
运行dingdang.py出现Exception AttributeError: "'PocketSphinxSTT' object has no attribute '_logfile'" 

### ISSUE THREAD

**Issue by 4XV** [wzpan/dingdang-robot#66]
配置完运行环境之后运行dingdang.py出现如下错误（PocketSphinx 已经成功安装）
Exception AttributeError: "'PocketSphinxSTT' object has no attribute '_logfile'" in <bound method PocketSphinxSTT.__del__ of <client.stt.PocketSphinxSTT object at 0x757cb2f0>> ignored

**Comment by wzpan** [comment]
请补充下您的系统环境信息。

**Comment by wzpan** [comment]
信息提供不足，难以诊断。暂时关闭本issue。如有补充再重新打开。
