### ISSUE TITLE
请教麦克风的选取

### ISSUE THREAD

**Issue by joln** [wzpan/dingdang-robot#7]
麦克风一定要选择全向的么？目前TB上全向的价格不一，实验用那种合适？

**Comment by wzpan** [comment]
@joln 建议选用阵列麦克风模块，根据阵列数量的不同价格也会有所不同。QQ群有时候会组织阵列模块的团购，可以争取到一些优惠，可以进群关注。

**Comment by wzpan** [comment]
关于麦克风的选择，我写了一份 [硬件选购建议](https://github.com/wzpan/dingdang-robot/wiki/hardware-choices) ，供参考。
