### ISSUE TITLE
唤醒后识别不到指令 报 "Nothing has been said or transcribed"

### ISSUE THREAD

**Issue by shark526** [wzpan/dingdang-robot#72]
hi, 请教下， 最新镜像烧录， 用的树莓派2+ PS3 Eye  + AUX 3.5 口外接音箱。 录音测试正常，可以唤醒，但是无法识别指令， 报 "Nothing has been said or transcribed"。
百度语音API用自带的和我自己申请的都试过，效果一样。
请指教， 谢谢。

**Comment by wzpan** [comment]
[常见问题](https://github.com/wzpan/dingdang-robot/wiki/troubleshooting) - 叮当总是过快结束主动聆听

**Comment by shark526** [comment]
好，今天回去试试。 谢谢 @wzpan

**Comment by shark526** [comment]
已解决， 是我没掌握说话时机， 又看demo的时候才发现，应该在第一声提示音播放后立马说话。mic妥妥的，没毛病。
