### ISSUE TITLE
拍照功能修改建议

### ISSUE THREAD

**Issue by zanjie1999** [wzpan/dingdang-robot#74]
/client/plugins/camera.py 107行
`if sendToUser(profile, wxbot, u"这是刚刚为您拍摄的照片", "", [dest_file], []):`
改为
`if sendToUser(profile, wxbot, u"这是刚刚为您拍摄的照片", "", [], [dest_file]):`
发送图片而不是发送文件,便于手机端查看(反正可以查看原图)

另外查看代码发现如果需要配置usb摄像头,需要在配置文件中添加
`usb_camera: "/dev/video0"`
来配置usb摄像头,并且还要安装 `fswebcam` 用于拍照
建议加入wiki

**Comment by wzpan** [comment]
done

另外，`usb_camera` 一项不需要指定路径那么详细，只需要填写值为 true 即可。
