### ISSUE TITLE
Your Weiyun Share of version 0.1.4 has been canceled. 你0.1.4的微云分享被取消了。

### ISSUE THREAD

**Issue by GoldJohnKing** [wzpan/dingdang-robot#8]
Your Weiyun Share of version 0.1.4 has been canceled.
你0.1.4的微云分享被取消了。

百度云分享尚可使用，但是下载太慢了，希望能够恢复微云分享。
为避免封杀，可用7z加密码压缩后上传。

**Comment by wzpan** [comment]
倒不是封杀的问题。只是微云非会员每7天分享链接就会失效。只能跟我说一声，到他们站点重新分享一次才能恢复。
我又恢复了一次下载链接。
如果您有会员，不妨帮忙提供个永久下载链接。
