### ISSUE TITLE
在笔记本上安装成功，但反映比较慢

### ISSUE THREAD

**Issue by nescat** [wzpan/dingdang-robot#81]
您好！感谢您的工作，让我有尝试自己开发智能音箱的机会！
我尚未在树莓派上安装，但我在笔记本上安装成功，使用笔记本自带mic和speaker，可正常唤醒叮当，但是唤醒后每说一句话都要等很久才能得到回答，看过log发现每次说完话要等好秒，才会出现识别出的文字语句，然后这些语句会送去图灵机器人找答案，这个速度到罢了，然后答案会被使用语音合成念出来，整个过程有时需要４到５秒，这个速度有点太慢了，请问有什么方法可以提高整个的反映速度吗？
需要安装ＳＤＫ做离线识别吗？在识别不了的情况下在送去做在线识别吗？
ｐｓ：掐过表，最慢要１１秒才开始回答问话

**Comment by shark526** [comment]
昨天对常用语音做了缓存功能（还没有合并过来）， 响应速度会有所提升， 如果你想试试效果可以去我的分支上拉下来看看

**Comment by wzpan** [comment]
已合并，可以试试

**Comment by wzpan** [comment]
v0.2.1 已经对响应速度进行了优化。请升级体验。关闭本 issue 。
