### ISSUE TITLE
Gmail如何配置

### ISSUE THREAD

**Issue by SkyAzure** [wzpan/dingdang-robot#89]
```
    smtp_server: 'smtp.google.com'
    smtp_port: ''  # 这里填写非SSL协议端口号
    imap_server: 'imap.google.com'
    imap_port: '' # 这里填写非SSL协议端口号
```
配置错误

**Comment by helloyinwei** [comment]
smtp_server: 'smtp.gmail.com'
smtp_port: '587'
imap_server: 'imap.gmail.com'
imap_port: '993'
Gmail IMAP强制要求SSL，需要把/client/plugins/Email.py 中 imaplib.IMAP4 改为 imaplib.IMAP4_SSL

**Comment by olive900** [comment]
测试这种方法对126.com邮箱好像不管用

**Comment by wzpan** [comment]
126邮箱请保持默认的配置方式，另外详见wiki里的网易邮箱说明
